version: '3.1'

services:
  codrr_pg:
    image: postgres:16.4
    container_name: codrr_pg
    restart: always
    environment:
      POSTGRES_DB: cursodb
      POSTGRES_USER: blclN
      POSTGRES_PASSWORD: nestDoc9
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432